# Generated by Django 3.2.11 on 2024-07-16 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.company'),
        ),
    ]
