# Generated by Django 5.0.7 on 2024-07-25 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_cliente_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='company',
        ),
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.company'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servicos', to='home.cliente'),
        ),
        migrations.DeleteModel(
            name='CompanyUser',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
