# Generated by Django 5.0.7 on 2024-08-01 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_statusproject_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='bot_id',
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.statusproject'),
        ),
    ]
