# Generated by Django 5.0.7 on 2024-08-06 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_project_data_entrega_project_responsavel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servico',
            name='cliente',
        ),
        migrations.AddField(
            model_name='cliente',
            name='servicos',
            field=models.ManyToManyField(blank=True, to='home.servico'),
        ),
    ]
