# Generated by Django 5.0.7 on 2024-08-06 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_servico_cliente_cliente_servicos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='servicos',
        ),
        migrations.AddField(
            model_name='servico',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servicos', to='home.cliente'),
        ),
    ]
