# Generated by Django 5.0.7 on 2024-07-25 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0003_remove_user_company_remove_user_groups_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanalOmini',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EmpresasOmini',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('timezone', models.CharField(max_length=50)),
                ('external_id', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('ligado', 'Ligado'), ('desligado', 'Desligado')], default='desligado', max_length=10)),
                ('bot_id', models.CharField(max_length=255)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bots', to='home.cliente')),
                ('tipo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.tiposervico')),
                ('canais', models.ManyToManyField(blank=True, to='ligobots.canalomini')),
            ],
        ),
        migrations.CreateModel(
            name='BotCanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=15, null=True)),
                ('status', models.CharField(choices=[('ligado', 'Ligado'), ('desligado', 'Desligado')], default='desligado', max_length=10)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_canais', to='ligobots.bot')),
                ('canal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ligobots.canalomini')),
            ],
        ),
        migrations.CreateModel(
            name='Licenca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], default='ativo', max_length=10)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licencas', to='ligobots.empresasomini')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ligobots.perfilusuario')),
            ],
        ),
        migrations.CreateModel(
            name='LicencaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licenca_usuarios', to='ligobots.empresasomini')),
                ('licenca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licenca_usuarios', to='ligobots.licenca')),
            ],
        ),
    ]
