# Generated by Django 5.0.7 on 2024-07-25 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligobots', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='licenca',
            name='perfil',
        ),
        migrations.AddField(
            model_name='licencausuario',
            name='perfil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ligobots.perfilusuario'),
        ),
    ]
