# Generated by Django 5.0.7 on 2024-07-26 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligobots', '0002_remove_licenca_perfil_licencausuario_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='bot_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
