# Generated by Django 5.0.7 on 2024-07-26 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_user_company_remove_user_groups_and_more'),
        ('ligobots', '0003_alter_bot_bot_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rpa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('ligado', 'Ligado'), ('desligado', 'Desligado')], default='desligado', max_length=10)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rpas', to='home.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Ura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('ligado', 'Ligado'), ('desligado', 'Desligado')], default='desligado', max_length=10)),
                ('ura_id', models.CharField(max_length=255)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uras', to='home.cliente')),
            ],
        ),
    ]
