# Generated by Django 5.0.7 on 2024-08-12 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligobots', '0004_rpa_ura'),
    ]

    operations = [
        migrations.AddField(
            model_name='ura',
            name='ativa',
            field=models.BooleanField(default=True),
        ),
    ]
